class VerifyError(Exception):
    """An Exception occurred when a verification process failed."""
    pass
